kind: Deployment
metadata:
  name: learning-platform-error-handler
  labels:
    app: learning-platform-error-handler
    group: applications
    version: v1 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learning-platform-error-handler
      group: applications
  template:
    metadata:
      name: learning-platform-error-handler
      labels:
        app: learning-platform-error-handler
        group: applications
        version: v1
    spec:
      subdomain: applications
      containers: 
      - name: learning-platform-error-handler-application
        image: manolispapd/service-app:latest
        imagePullPolicy: Always
        ports: 
        - name: http
          containerPort: 8080