kind: Deployment
metadata:
  name: learning-platform-frontend
  labels:
    app: learning-platform-frontend
    group: applications
    version: v1 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learning-platform-frontend
      group: applications
  template:
    metadata:
      name: learning-platform-frontend
      labels:
        app: learning-platform-frontend
        group: applications
        version: v1
    spec:
      subdomain: applications
      containers: 
      - name: learning-platform-frontend-application
        image: valkongr/my-game-app:latest
        imagePullPolicy: Always
        ports: 
        - name: http
          containerPort: 8080