apiVersion: v1
kind: Service
metadata:
  name: learning-platform-frontend
  labels:
    app: learning-platform-frontend
    group: applications
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: learning-platform-frontend
    group: applications