repositories:
  url: https://github.com/ManolisPapdOrg/manifests.git

environment: dev

applications:
  - id: learningPlatformFrontend
    name: learning-platform-frontend
    enabled: true
    ingress: true
    image: valkongr/myfrontend:latest
    replicas: 1
    route:
      probe: "/#/"
      prefix: "/"
      port: 3000
    mount: ""
    volume: ""
    observability: false