# {{- range $application:= .Values.applications}}
# {{- if $application.enabled}}
# --- 
# apiVersion: v1
# kind: Service
# metadata:
#     name: {{ $application.name }}
#     labels:
#         app: {{ $application.name }}
#         group: {{ $.Chart.Name }}
# spec:
#     type: NodePort
#     ports:
#         - name: http
#           port: {{ $application.route.port }}
#           targetPort: 3000
#           protocol: TCP
#     selector:
#         app: {{ $application.name }}
#         group: {{ $.Chart.Name }}
# {{- end }}
# {{- end }}

apiVersion: v1
kind: Service
metadata:
  name: learning-platform-frontend
spec:
  type: NodePort
  selector:
    app: learning-platform-frontend
    version: 2.0.0
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80