{{- range $application:= .Values.applications}}
{{- if $application.enabled}}
--- 
apiVersion: v1
kind: Service
metadata:
    name: {{ $application.name }}
    labels:
        app: {{ $application.name }}
        group: {{ $.Chart.Name }}
spec:
    ports:
        - name: http
          port: {{ $application.route.port }}
          targetPort: http
    selector:
        app: {{ $application.name }}
        group: {{ $.Chart.Name }}
{{- end }}
{{- end }}